---
- name: lab4 Playbook
  hosts: all
  tasks:
    - name: Run a command
      command: free -h
      register: server_resource

    - name: Show the server resource
      debug:
        msg: "{{ server_resource.stdout }}"


    - name: Show the node servers IP address
      command: hostname -I
      register: server_ip

    - name: Display the server IP
      debug:
        msg: IPv4 address of each server is {{ server_ip.stdout }}
