---
- name: Working with variables
  hosts: node1
  vars:
    fav_color: yellow
    port_nums: [21,22,23,25,80,443]    
    users:
      bob:
        username: bob
        uid: 1122
        shell: /bin/bash

      lisa:
        username: lisa
        uid: 2233
        shell: /bin/sh
  tasks:
    - name: Show me fav_color value
      debug:
        msg: My favorite color is {{ fav_color }}.

    - name: Show 2nd item in port_nums
      debug:
        msg: SSH port is {{ port_nums[1] }}

    - name: Show the uid of bob
      debug:
        msg: Bob's uid is {{ users.bob.uid }}
